package sx.lambda.voxel.api;

public final class BuiltInBlockIds {

        public static final int
                STONE_ID = 1,
                DIRT_ID  = 3,
                GRASS_ID = 2,
                COBBLESTONE_ID = 4,
                BEDROCK_ID = 7,
                GRAVEL_ID = 13,
                IRON_ORE_ID = 15,
                COAL_ORE_ID = 16,
                REDSTONE_ORE_ID = 73,
                GOLD_ORE_ID = 14,
                DIAMOND_ORE_ID = 56,
                LAPIS_ORE_ID = 21,
                EMERALD_ORE_ID = 129,
                OBSIDIAN_ID = 49,
                STONE_MONSTER_EGG_ID = 97,
                SNOW_ID = 78,
                SAND_ID = 12,
                WATER_ID = 8,
                WATER_FLOW_ID = 9,
                LAVA_FLOW_ID = 10,
                LAVA_STILL_ID = 11,
                PLANKS_ID = 5,
                LOG_ID = 17,
                LOG_TWO_ID = 162,
                LEAVES_TWO_ID = 161,
                LEAVES_ID = 18,
                STONE_BRICK_ID = 98,
                TALL_GRASS_ID = 31,
                FLOWER_ID = 175,
                FLOWER_TWO_ID = 37,
                FLOWER_THREE_ID = 38,
                BROWN_MUSHROOM_BLOCK_ID = 99,
                RED_MUSHROOM_BLOCK_ID = 100,
                CLAY_ID = 82,
                SUGAR_CANE_ID = 83,
                MOSS_STONE_ID = 48,
                BROWN_MUSHROOM_ID = 39,
                RED_MUSHROOM_ID = 40,
                FENCE_ID = 85,
                UNKNOWN_ID = 1023;

}
